service: imageUploader

frameworkVersion: '2'

custom:
  prune:
    automatic: true
    number: 3
  bucket: getting-started-lambda-example-jaggy
  config: ${file(configurations/${env:STAGE}.json)}
  stages:
    - ${env.STAGE}
  alerts:
    stages:
      - ${env.STAGE}
    topics:
      alarm:
        topic: ${self:service}-${env:STAGE}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: yorjaggy@gmail.com
    alarms:
      - functionErrors
      - functionThrottles

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - ./**
    - "node_modules/"
    - package.json
  include:
    - uploadImage.js
    - src/**
    - configurations/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.config.stage}
  lambdaHashingVersion: '20201221'
  region: ${self:custom.config.region}
  tracing:
    lambda: true
    apiGateway: true
  layers:
    - arn:aws:lambda:us-east-1:869315223613:layer:myFirstCapa:5
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
          - "s3:PutObject" 
        Resource: 
          - "arn:aws:s3:::${self:custom.bucket}/*"
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
          - codedeploy:*
        Resource: "*"

functions:
  api:
    handler: uploadImage.handler
    events:
      - http:
          path: upload
          method: post
          cors: true
      - http:
          path: health
          method: any
          cors: true
      - http:
          path: canary
          method: get
          cors: true
      - http:
          path: suma
          method: post
          cors: true
    deploymentSettings:
      type: AllAtOnce
      alias: Live
      postTrafficHook: postHook
      # alarms:
      #   - FooAlarm          # When a string is provided, it expects the alarm Logical ID
      #   - name: BarAlarm    # When an object is provided, it expects the alarm name in the name property
    environment:
      Bucket: ${self:custom.bucket}

  postHook:
    handler: src/hooks/hookRollback.post

resources:
  Resources:
    StorageBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:custom.bucket}

plugins:
  - serverless-offline
  - serverless-plugin-canary-deployments
  - serverless-plugin-aws-alerts
  - serverless-prune-plugin
  # - serverless-api-stage
  # - serverless-domain-manager
  # - serverless-apigw-binary
  # - serverless-plugin-warmup
  # - serverless-plugin-log-subscription
